### PR TITLE
Update all dependencies and re-implement electrode-bundle-analyzer

### PR DESCRIPTION
**Pull request by jdori**
Made this change to fix a problem where lib/js and lib/es6 were disappearing upon making changes to the project while running the app with `yarn start`

### CODE REVIEW

**Comment by wyze** [comment]
Hey @jdori, would you mind bumping these up to the latest again and I will get it merged in!

**Comment by jdori** [comment]
Done! Make sure you merge from 5ee2b4, as it reverts some on-save syntax changes that are beyond the scope of this PR in my opinion.

**Comment by jdori** [comment]
I went ahead and updated all dependencies by the way. I successfully ran `yarn start`, but I did not compare compiler warnings befor vs after the dependency bumps.

**Comment by wyze** [comment]
I pulled it down and did a fresh install then `yarn test`, and it looks like the `webpack-common-shake` plugin isn't compatible with webpack 4 yet.

**Comment by jdori** [comment]
Dang, okay. I’ll have some time in around four hours to fix that.

**Comment by jdori** [comment]
Should be good to go ✌️. By the way, what dependency should `analyze-bundle` in the analyze command use?

**Comment by wyze** [comment]
It looks like that command wouldn't even work right now. The dependency that provides that binary is `electrode-bundle-analyzer`. It was added in https://github.com/reasonml-community/reason-react-hacker-news/commit/3d6de3fada62938c27b152584bf59af317ddce22 then removed in https://github.com/reasonml-community/reason-react-hacker-news/commit/23b06db8b5e7a369d4fd1b85a259aba269cac21f

**Comment by jdori** [comment]
I’m happy to re-implement it. I imagine this project serving as a launching point for people interested in learning reason-react, so having the ability to run a bundle analysis off a freshly-cloned repo seems relevant to me, especially for folks running into webpack for the first time. What do you think?

**Comment by jdori** [comment]
Added the latest version of [electrode-bundle-analyzer](https://github.com/electrode-io/electrode-bundle-analyzer) as a dev dependency in 22e4798.

**Comment by jdori** [comment]
Just checking in. We good to merge?

**Comment by jdori** [comment]
Nothing wrong with frequent releases! 😀

**Comment by wyze** [comment]
Thanks, looks good!

**Pull request merged**
